import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./com/NavBar";
import CanvasParticle from "./com/CanvasParticle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CanvasParticle />
        <NavBar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
